sudo: required
language: java
jdk:
  - openjdk11
services:
  - docker
cache:
  directories:
    - $HOME/.m2
env:
  global:
    # AWS_ACCESS_KEY_ID
    - secure: djNyY+v+zqtudRJWHVpjWH04es1PB4M+8rfpyTWtnBEArK8oYXUtRNI+saVlGWpGrhLN14IaYJY+sEkF3WhT6Qo0GyFyqaccZddd6Dax0dcQDAmp6defCfOC4S92y8SyrenWV6HNpokLQrPatdTdE8lctOZdv5UBGPR4OBn9OwtSU5kvzbT1BkGtwz+6XgKSeLvIRL5rgZ+SfgbdMLrLjYEmmZ9y6Cl+7LZayNUg9xsnDVZQajGT4crjti1cD8qvLk6ZMPaprzBdyLJIy440E8wG1tNQCi0I93DXikx03uC9UPvM4GfoSMiOFjd5RzoyCo+ExZmNE5dFDNrtsomw7AEA9q6l358Ei8xIJzolu0VB1WjOTbYZTawX15nn71/amXAkNeNQJke+Tz8Hmz2Dw2hcTfPkdVrLOJ5OFqeHZp6zrNdjS0sTfjouI3B7LNEjfilQdgBRM5FrmrptSaNvxbhKJWXsf9MxwUaa1EpPBsuoveF+12wxXFK/UOXsE1gN00vyLCVo3OK+6NZuEhWaD13WeWejj8h735huLOc1be0Xyo7z3zUElI1KvCvfT2VYiyViMewC3Vrxt1QOm6PjsbdjWeMO3p6LXq8No8dh8+dJVIKRGlc+PsbasJpgBEYGGCZnximRruynzzK8m2SQMREtv2iztLVDqAIk20oECZo=
    # AWS_SECRET_ACCESS_KEY
    - secure: S9lD1ICzuCRqfmllZsT7Jm84+pMyioKQmL3e6ZD5EnI/KX4oM+EccNx3ns+ZkWRpUrwzvMhXDp9vs4dtwkNQJLnr27JbgMMZWAKW3CQbwtSLLLjjNIxq8QfsnN7K/a2xmKkdqO314/q9nYNmWsDjVvXShJMsKCsTaY+DXYRb8VtABRboJuK0ZQX+NUF//brZCAkcB59D+RaTGEoeMC484RQ/IFABO6lyKEHAzuQyKZU04Kbz8WW1W6ovRDt4q6FClJB2Vh0cmwDHXcB24W9rcG7oYvbReh99Fn/xkRIyBJbi1BTLX5fuieGRuA5rLBGfbDQ+TLI85aOh5kcW96y9hlzyI7eO3zqGdke12wp1yfGBqJJkw5qV/nMkTovZkIf/yEqndnczzu+BduNIJ/WtwXV8zSUD2CbZAyjJTnzG/SKHvngzBenGYtGWkvx1/N/OY6Gxn4blDTEGx7T2qonNSYOYzMZwxO6L3fHCIFFjkIQB79MgrpuOwwC5f9j3gFvemOfbZL/rkNttozvtpnAI5Btun+dU9udNqeLBrG0G/giymwBrX53qmKSp+VoX+Szn1XoTROma0C8qRUuj9h4SI5v3X1OdKKid6zhJ7fRggvp/NVkU48NXJ8rUQLS1KyOc77c6F/jJUWEIBpXWsrGWOvsqmMZZqboTlaQz0pL7nqc=

install:
  - git clone https://github.com/Opetushallitus/ci-tools.git
  - source ci-tools/common/setup-tools.sh
  - export ARTIFACT_NAME="oikeustulkkirekisteri"

script:
  - mvn clean install -B -Dbranch=${TRAVIS_BRANCH} -Drevision=${TRAVIS_COMMIT} -DbuildNumber=${TRAVIS_BUILD_NUMBER}

  - mv oikeustulkkirekisteri-service/target/oikeustulkkirekisteri-service.war $DOCKER_BUILD_DIR/artifact/oikeustulkkirekisteri-service.war
  - mv oikeustulkkirekisteri-ui/target/oikeustulkkirekisteri-ui-*.war $DOCKER_BUILD_DIR/artifact/oikeustulkkirekisteri-ui.war
  - mv oikeustulkkirekisteri-public-ui/target/oikeustulkkirekisteri-public-ui-*.war $DOCKER_BUILD_DIR/artifact/oikeustulkkirekisteri-public-ui.war
  - cp -vr src/main/resources/oph-configuration $DOCKER_BUILD_DIR/config/

  - export BASE_IMAGE="baseimage-war-openjdk11:master"
  - ./ci-tools/common/pull-image.sh
  - ./ci-tools/build/build-war.sh $ARTIFACT_NAME

deploy:
  - provider: script
    script: ./ci-tools/build/upload-image.sh $ARTIFACT_NAME
    on:
      all_branches: true
