ALTER TABLE oikeustulkki ADD COLUMN poistettu BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE oikeustulkki ADD COLUMN poistohetki TIMESTAMP;
ALTER TABLE oikeustulkki ADD COLUMN poistaja TEXT;
ALTER TABLE oikeustulkki ADD COLUMN version INT8 NOT NULL DEFAULT 0;

ALTER TABLE tulkki ADD COLUMN poistettu BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE tulkki ADD COLUMN poistohetki TIMESTAMP;
ALTER TABLE tulkki ADD COLUMN poistaja TEXT;
ALTER TABLE tulkki ADD COLUMN version INT8 NOT NULL DEFAULT 0;
